-- MySQL Script generated by MySQL Workbench
-- seg 02 out 2023 20:10:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dw
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dw
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dw` DEFAULT CHARACTER SET utf8 ;
USE `dw` ;

-- -----------------------------------------------------
-- Table `dw`.`DIM_TEMPO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw`.`DIM_TEMPO` (
  `data_referencia` DATE,
  `ano` INT NULL DEFAULT NULL,
  `trimestre` INT NULL DEFAULT NULL,
  `mes` VARCHAR(50) NULL DEFAULT NULL,
  `dia_da_semana` VARCHAR(50) NULL DEFAULT NULL,
  `flag_feriado` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`data_referencia`));


-- -----------------------------------------------------
-- Table `dw`.`DIM_CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw`.`DIM_CLIENTE` (
  `id_cliente` INT,
  `nm_completo_cliente` VARCHAR(150) NULL DEFAULT NULL,
  `ie_sexo` CHAR(1) NULL DEFAULT NULL,
  `qt_tempo_dias_cadastro` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_cliente`));


-- -----------------------------------------------------
-- Table `dw`.`DIM_FILME`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw`.`DIM_FILME` (
  `id_filme` INT,
  `nm_filme` VARCHAR(255) NULL DEFAULT NULL,
  `ds_categoria_principal` VARCHAR(25) NULL DEFAULT NULL,
  `ds_categoria_secundaria` VARCHAR(25) NULL DEFAULT NULL,
  `ds_idioma` CHAR(20) NULL DEFAULT NULL,
  `nr_ano_lancamento` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_filme`));


-- -----------------------------------------------------
-- Table `dw`.`DIM_FUNCIONARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw`.`DIM_FUNCIONARIO` (
  `id_funcionario` INT ,
  `nm_completo_funcionario` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id_funcionario`));


-- -----------------------------------------------------
-- Table `dw`.`FATO_LOCACAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw`.`FATO_LOCACAO` (
  `id_locacao` INT,
  `id_cliente` INT,
  `id_filme` INT,
  `id_funcionario` INT ,
  `qt_dias_locacao` INT ,
  `ie_pago` TINYINT,
  `dt_locacao` DATE,
  `vl_pago` DECIMAL(5,2),
  PRIMARY KEY (`id_locacao`),
  INDEX (`dt_locacao` ASC) VISIBLE,
  INDEX (`id_cliente` ASC) VISIBLE,
  INDEX (`id_filme` ASC) VISIBLE,
  INDEX (`id_funcionario` ASC) VISIBLE,
  CONSTRAINT `dt_locacao_dt`
    FOREIGN KEY (`dt_locacao`)
    REFERENCES `dw`.`DIM_TEMPO` (`data_referencia`),
  CONSTRAINT `dim_cliente_tempo`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `dw`.`DIM_CLIENTE` (`id_cliente`),
  CONSTRAINT `dim_filme_filme`
    FOREIGN KEY (`id_filme`)
    REFERENCES `dw`.`DIM_FILME` (`id_filme`),
  CONSTRAINT `fim_func_func`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `dw`.`DIM_FUNCIONARIO` (`id_funcionario`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
